config/routes.rb
Rails.application.routes.draw do
    root 'sessions#new'
    get    '/login',   to: 'sessions#new'
    post   '/login',   to: 'sessions#create'
    delete '/logout',  to: 'sessions#destroy'
    resources :users
    resources :posts, only: [:index, :show] do
      resources :comments
    end
    resources :posts, only: [:show] do
      resources :hashtags , only: [:create]
    end
    resources :hashtags, only: [:show]
    namespace :user do
      resources :posts
    end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/hashtag.rb
class Hashtag < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :hashtags
end

app/models/user.rb
class User < ActiveRecord::Base
  validate :image_size_validation
  has_many :posts
  has_many :comments
  has_secure_password
  mount_uploader :image, ImageUploader

  private
  def image_size_validation
    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :logged_in_user, only: [:create, :destroy]
  def create
    @comment = Comment.new(comment_params)
    @comment.post = Post.find(params[:post_id])
    @comment.user = current_user
    @comment.save
    redirect_to :back
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to :back
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = Hashtag.find(params[:id])
    @hashtags = Hashtag.where(name: @hashtag.name)
  end

  def create
    @hashtag = Hashtag.new(hash_params)
    @hashtag.post = Post.find(params[:post_id])
    @hashtag.save
    redirect_to :back
  end

  private
  def hash_params
    params.require(:hashtag).permit(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :logged_in_user, only: [:edit, :update, :index ,:show]
    def index
      @posts = Post.all.paginate(page: params[:page],per_page:6)
    end
    def create
    end

    def show
      @post = Post.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
      log_out
    end
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash.now[:success] = 'success'
      log_in user
      redirect_to posts_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :get_post, only: [:destroy,:show,:edit,:update]
  def index

  end
  def create
    @user = current_user
    @post = @user.posts.create(params.require(:post).permit(:title, :body))
    redirect_to user_post_path(@post)
  end
  def show
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end
  def edit
  end
  def update
    respond_to do |format|
      if(@post.update(post_params))
        format.html{redirect_to user_post_path,notice: 'Post updated successfully'}
      end
    end
  end



  private
  def get_post
    @post = Post.find(params[:id]) rescue nil
  end
  def post_params
    params.require(:post).permit(:title, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
protect_from_forgery
before_action :logged_in_users, only: [:edit, :update]
  def index
    @user = current_user
  end
  def create
    @user  = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to posts_path
    end
  end
  def show
    @user = current_user
    @posts = Post.all
  end
  def new
  end
  def edit
    @user = current_user
  end

  def update
    if(current_user.update_attributes(user_params))
      flash[:success] = "Profile updated"
      redirect_to posts_path
    end
  end

  private
  def user_params
      params.require(:user).permit(:username, :email, :password, :image ,:remove_image)
  end
  def logged_in_users
      unless logged_in? && current_user == User.find(params[:id])
          flash[:danger] = "Please log in."
          log_out
          redirect_to login_url
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
   session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  def logged_in_user
      unless logged_in?
        redirect_to root_url
      end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hashtags/show.html.erb
<table cellpadding="5">
  <% @hashtags.each do |hashtag| %>
    <tr>
      <td style="color: gray;font-size: 20px"><b><%= hashtag.post.user.username%></b></td>
    </tr>
    <tr>
      <td style="font-size: 18px"><b>title:</b> <i><%= hashtag.post.title %></i></td>
    </tr>
    <tr>
      <td>body: <i><%= hashtag.post.body %></i></td>
      <td style="float:right"><%= link_to "Show",user_post_path(hashtag.post) %></td>
    </tr>
  <% end %>
<table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<style>
ul {
  list-style-type: none;
  height: 30px;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: teal;
}
</style>
<% if logged_in? %>
<ul>
  <%= link_to "Home", posts_path ,:style => 'color: #FFFFFF; text_align: center;padding: 14px 16px;'%>
  <%= link_to "Add Post", user_posts_path ,:style => 'color: #FFFFFF; text_align: center;padding: 14px 16px;'%>
  <%= link_to "Update User Profile", edit_user_path(current_user.id),:style => 'color: #FFFFFF;text_align: center;padding: 14px 16px;' %>
  <%= link_to "Back", request.env['HTTP_REFERER'] ,:style => 'color: #FFFFFF;text_align: center;padding: 14px 16px;'%>
  <%= link_to "logout", logout_path ,:method => :delete,:style => 'color: #FFFFFF;text_align: center;float: right'%>
</ul>
<% end %>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>




</html>

app/views/posts/index.html.erb
<h1> Posts</h1>
<table cellpadding="5">
  <% @posts.each do |post| %>
    <tr>
      <td style="color: gray;font-size: 20px"><b><%= post.user.username%></b></td>
    </tr>
    <tr>
      <td style="font-size: 18px"><b>title:</b> <i><%= post.title %></i></td>
    </tr>
    <tr>
      <td>body: <i><%= post.body %></i></td>
      <td style="float:right"><%= link_to "Show",user_post_path(post) %></td>
    </tr>
  <% end %>
<table>
<%= will_paginate @posts %>

app/views/user/posts/edit.html.erb
<% provide(:title, "Update Post") %>
<h1>Update Post</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:post,url:user_post_path,:method => :put ) do |f| %>

      <%= f.label :title %>
      <br>
      <%= f.text_field :title, class: 'form-control' %>
      <br>
      <br>
      <%= f.label :body %>
      <br>
      <%= f.text_area :body, class: 'form-control',:rows => 10, style: 'width:80%;' %>
      <br>
      <br>
      <%= f.submit "Update", class: "btn btn-primary", style: 'width:20%;color: black;background-color: LightSeagreen ;height:30px' %>
    <% end %>
  </div>
</div>

app/views/user/posts/index.html.erb
<% provide(:title, "Add Post") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:post,url:user_posts_path) do |f| %>
      <h1>Add new Post</h1>
      <% if current_user.image?%>
        <%= image_tag current_user.image,style:'float: right;height: 250px;' %>
      <%end%>
      <%= f.label :title %>
      <br>
      <%= f.text_field :title,:required => true, class: 'form-control' %>
      <br>
      <br>
      <%= f.label :body %>
      <br>
      <%= f.text_area :body, class: 'form-control',:required => true,:rows => 10, style: 'width:80%;' %>
      <br>
      <br>
      <%= f.submit "Add Post", class: "btn btn-primary", style: 'width:20%;color: black;background-color: LightSeagreen ;height:30px' %>
      <br>


    <% end %>

  </div>
</div>

app/views/user/posts/show.html.erb
<table>
    <tr>
      <td>author: <%= @post.user.username %></td>
    </tr>
    <tr>
      <td>title : <%= @post.title %></td>
    </tr>
    <tr>
      <td>body : <%= @post.body %></td>
    </tr>
    <tr>
    <td>hashtags: </td>
    <% @post.hashtags.each do |hashtag| %>
    <td><%= link_to hashtag.name, hashtag_path(hashtag) %> </td>
    <%end%>
    </tr>
    <tr>
      <td>
        <% if current_user == @post.user %>
          <%= button_to "Delete",user_post_path, :method => :delete,data: {confirm: 'Are you sure?'},style: 'color: black;background-color: LightSeagreen ;height:30px' %>
          <%= button_to "Edit",edit_user_post_path(@post),:method => :get,style: 'color: black;background-color: LightSeagreen ;height:30px' %>
        <% end %>
      </td>
    </tr>
</table>

<% if current_user == @post.user %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(:hashtag, url: post_hashtags_path(@post)) do |f| %>
        <br>
        <%= f.text_field :name, class: 'form-control'%>
        <%= f.submit "Add hashtag", class: "btn btn-primary",style: 'color: black;background-color: LightSeagreen' %>
      <% end %>
    </div>
  </div>
<%end%>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:comment, url: post_comments_path(@post)) do |f| %>
      <br>
      <%= f.text_area :body, class: 'form-control',:rows => 4, style: 'width:40%;' %>
      <br>
      <%= f.submit "Add comment", class: "btn btn-primary",style: 'width:20%;color: black;background-color: LightSeagreen ;height:30px ' %>
    <% end %>
  </div>
</div>

<h2>Comments</h2>
<table>
<% @post.comments.each do |comment| %>
  <tr>
    <td><b><%= comment.user.username %></b>: <%= comment.body %> </td>
  </tr>
  <tr>
    <td style="font-size: 12px;color:gray"><%= comment.updated_at%> </td>
  </tr>
  <tr>
    <td>
      <%if current_user == comment.user%>
        <%= button_to "Delete", "/posts/#{@post.id}/comments/#{comment.id}",:method => :delete,data: {confirm: 'Are you sure?'} ,style: 'width:80%;color: black;background-color: LightSeagreen ;height:30px '%>
      <% end %>
     </td>
  </tr>

<% end %>
</table>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update User</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, url: user_path, :method => :put) do |f| %>

      <%= f.label :username %>
      <br>
      <%= f.text_field :username, :required => true,class: 'form-control' %>
      <br><br>
      <%= f.label :email %>
      <br>
      <%= f.email_field :email,:required => true, class: 'form-control' %>
      <br><br>
      <%= f.label :password %>
      <br>
      <%= f.password_field :password,:required => true, class: 'form-control' %>
      <br><br>
      <% if current_user.image? %>
        <%= image_tag current_user.image.thumb.url %>
        <div>
          <%= label_tag :remove_image do %>
            Remove image
            <%= f.check_box :remove_image %>
          <% end %>
        </div>
    <% end %>
    <br><br>
    <%= f.label :image %>
    <br>
    <%= f.file_field :image%>
    <br><br>
      <%= f.submit "save", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:user, url: users_path) do |f| %>
      <%= f.label :username %>
      <br>
      <%= f.text_field :username,:required => true, class: 'form-control'%>
      <br>
      <br>
      <%= f.label :email %>
      <br>
      <%= f.email_field :email,:required => true, class: 'form-control' %>
      <br>
      <br>
      <%= f.label :password %>
      <br>
      <%= f.password_field :password, :required => true,class: 'form-control' %>
      <br>
      <br>
      <%= f.label :image %>
      <br>
      <%= f.file_field :image ,:accept =>"image/png,image/gif,image/jpeg,image/jpg"%>
      <br>
      <br>
      <%= f.submit "Sign up", class: "btn btn-primary",style: 'width:8%;color: black;background-color: LightSeagreen ;height:30px' %>

    <% end %>
  </div>
</div>